import { NextRequest, NextResponse } from 'next/server';
import { Resend } from 'resend';

const resend = new Resend(process.env.RESEND_API_KEY);

export async function POST(request: NextRequest) {
  try {
    const { to, subject, messages, vehicle, mode, html } = await request.json();
    
    console.log('Email API called with:', { to, messageCount: messages?.length, vehicle, mode, hasHtml: !!html });

    // If HTML is provided directly (for welcome emails, etc.), send it
    if (html && to && subject) {
      const data = await resend.emails.send({
        from: 'Mechanic AI <noreply@codingeverest.com>',
        to: [to],
        subject: subject,
        html: html,
      });

      console.log('Email sent successfully:', data);
      return NextResponse.json({ success: true, data });
    }

    // Otherwise, it's a diagnostic report - require messages
    if (!to || !messages || messages.length === 0) {
      console.log('Missing required fields for email');
      return NextResponse.json(
        { error: 'Missing required fields' },
        { status: 400 }
      );
    }

    const reportDate = new Date().toLocaleDateString('en-US', { 
      year: 'numeric', 
      month: 'long', 
      day: 'numeric' 
    });

    // Create plain text version
    const textContent = `
MECHANIC AI - PROFESSIONAL DIAGNOSTIC REPORT
============================================

Report Date: ${reportDate}
Report ID: #${Date.now().toString().slice(-8)}
Vehicle: ${vehicle.year} ${vehicle.make} ${vehicle.model}
Diagnostic Mode: ${mode === 'casual' ? 'Casual' : 'Professional Mechanic'}

DIAGNOSTIC CONVERSATION
-----------------------

${messages.map((msg: any) => `
${msg.role === 'user' ? 'CUSTOMER' : 'MECHANIC AI'}:
${msg.content}
`).join('\n---\n')}

IMPORTANT DISCLAIMER
--------------------
This diagnostic report is generated by an AI assistant and should be used for informational purposes only. Always consult with a certified, licensed mechanic before performing any repairs or maintenance on your vehicle.

---
Mechanic AI | AI-Powered Vehicle Diagnostics
Generated on ${reportDate}
    `.trim();

    const conversationHTML = messages
      .map((msg: any, index: number) => {
        const content = msg.content || '';
        const role = msg.role || 'user';
        
        // Format content with section headers styled
        const formattedContent = content.split('\n').map((line: string) => {
          // Check if line is a section header (all caps followed by colon)
          const isSectionHeader = /^[A-Z\s]+:$/.test(line.trim());
          
          if (isSectionHeader) {
            return `<div style="color: #ef4444; font-weight: 600; font-size: 15px; margin-top: 15px; margin-bottom: 8px; letter-spacing: 0.05em;">${line}</div>`;
          }
          
          return line;
        }).join('<br>');
        
        return `
        <div style="margin-bottom: 25px;">
          <div style="font-weight: 600; font-size: 13px; text-transform: uppercase; letter-spacing: 0.5px; margin-bottom: 8px; color: ${role === 'user' ? '#2563eb' : '#ef4444'};">
            ${role === 'user' ? 'CUSTOMER' : 'MECHANIC AI DIAGNOSIS'}
          </div>
          <div style="background: #f8f9fa; padding: 18px; border-radius: 8px; border-left: 4px solid ${role === 'user' ? '#2563eb' : '#ef4444'}; font-size: 15px; line-height: 1.7;">
            ${formattedContent}
          </div>
        </div>
      `;
      })
      .join('');
    
    console.log('Generated conversation HTML length:', conversationHTML.length);
    console.log('First 200 chars:', conversationHTML.substring(0, 200));

    const emailHtml = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333; margin: 0; padding: 0; background-color: #f5f5f5;">
  <div style="max-width: 700px; margin: 40px auto; background: white; border-radius: 12px; overflow: hidden;">
    
    <!-- Header -->
    <div style="background-color: #1a1a1a; color: white; padding: 40px 30px; text-align: center;">
      <div style="font-size: 36px; font-weight: bold; margin-bottom: 10px; color: white;">
        Mechanic <span style="color: #ef4444;">AI</span>
      </div>
      <p style="font-size: 16px; opacity: 0.9; margin: 0; color: white;">Professional Vehicle Diagnostic Report</p>
    </div>
    
    <!-- Content -->
    <div style="padding: 40px 30px;">
      
      <!-- Report Info -->
      <div style="background: #f8f9fa; padding: 25px; border-radius: 8px; margin-bottom: 35px; border-left: 4px solid #ef4444;">
        <table width="100%" cellpadding="0" cellspacing="0">
          <tr>
            <td width="50%" style="padding-right: 10px;">
              <div style="margin-bottom: 12px;">
                <div style="font-weight: 600; color: #555; font-size: 13px; text-transform: uppercase; letter-spacing: 0.5px; margin-bottom: 5px;">Report Date</div>
                <div style="font-size: 16px; color: #0a0a0a;">${reportDate}</div>
              </div>
              <div style="margin-bottom: 12px;">
                <div style="font-weight: 600; color: #555; font-size: 13px; text-transform: uppercase; letter-spacing: 0.5px; margin-bottom: 5px;">Report ID</div>
                <div style="font-size: 16px; color: #0a0a0a;">#${Date.now().toString().slice(-8)}</div>
              </div>
            </td>
            <td width="50%" style="padding-left: 10px;">
              <div style="margin-bottom: 12px;">
                <div style="font-weight: 600; color: #555; font-size: 13px; text-transform: uppercase; letter-spacing: 0.5px; margin-bottom: 5px;">Vehicle</div>
                <div style="font-size: 16px; color: #0a0a0a;">${vehicle.year} ${vehicle.make} ${vehicle.model}</div>
              </div>
              <div style="margin-bottom: 12px;">
                <div style="font-weight: 600; color: #555; font-size: 13px; text-transform: uppercase; letter-spacing: 0.5px; margin-bottom: 5px;">Diagnostic Mode</div>
                <div style="font-size: 16px; color: #0a0a0a;">${mode === 'casual' ? 'Casual' : 'Professional Mechanic'}</div>
              </div>
            </td>
          </tr>
        </table>
      </div>
      
      <!-- Section Title -->
      <div style="font-size: 22px; font-weight: 600; color: #0a0a0a; margin: 35px 0 20px 0; padding-bottom: 10px; border-bottom: 2px solid #e5e5e5;">
        Diagnostic Conversation
      </div>
      
      <!-- Messages -->
      ${conversationHTML}
      
      <!-- Disclaimer -->
      <div style="margin-top: 40px; padding: 20px; background: #fff3cd; border: 2px solid #ffc107; border-radius: 8px; font-size: 14px;">
        <div style="font-weight: 600; color: #856404; margin-bottom: 10px; font-size: 15px;">Important Disclaimer</div>
        <p style="margin: 0;">This diagnostic report is generated by an AI assistant and should be used for informational purposes only. Always consult with a certified, licensed mechanic before performing any repairs or maintenance on your vehicle.</p>
      </div>
      
    </div>
    
    <!-- Footer -->
    <div style="background: #f8f9fa; padding: 30px; text-align: center; color: #666; font-size: 13px; border-top: 1px solid #e5e5e5;">
      <div style="font-weight: 600; color: #0a0a0a; margin-bottom: 10px; font-size: 16px;">Mechanic AI</div>
      <p style="margin: 5px 0;">AI-Powered Vehicle Diagnostics | For Professional Use</p>
      <p style="margin: 10px 0 0 0;">Generated on ${reportDate}</p>
    </div>
    
  </div>
</body>
</html>
    `.trim();

    const data = await resend.emails.send({
      from: 'Mechanic AI <noreply@codingeverest.com>',
      to: [to],
      subject: subject || `Mechanic AI Diagnostic Report${vehicle.year || vehicle.make || vehicle.model ? ` - ${vehicle.year} ${vehicle.make} ${vehicle.model}`.trim() : ''}`,
      html: emailHtml,
      text: textContent,
    });

    console.log('Email sent successfully:', data);
    return NextResponse.json({ success: true, data });
  } catch (error) {
    console.error('Email error:', error);
    return NextResponse.json(
      { error: 'Failed to send email' },
      { status: 500 }
    );
  }
}
